### ISSUE TITLE
Sample app doesn't recognise voice after 1st intent.

### ISSUE THREAD

**Issue by voipterminator** [davehorton/simple-dialogflow-example#1]
I'm testing the DF integration as per this example and found an issue after detecting first intent.
In the app it is clearly stated that after playing back received audio with the intent, the app should start looking for other intents by listening to the voice on the channel.

[App.js - line 118](https://github.com/davehorton/simple-dialogflow-example/blob/master/app.js#L118)
 
What I found is the app actually doing voice recognition initially, then I'm getting the final transcript, finally getting an intent with the audio, the audio is being played as well and after that when starting the dialogflow again it is actually ignoring the voice from there. 

After 10 seconds of silence I'm getting critical error:
` [CRIT] google_glue.cpp:202 StreamingDetectIntentRequest finished with err While calling Cloud Speech API: Audio Timeout Error: Long duration elapsed without audio. Audio should be sent close to real time. (11):`

Freeswitch log: 
[FS_dialogflow_issue_after_first_intent.txt](https://github.com/davehorton/simple-dialogflow-example/files/3742796/FS_dialogflow_issue_after_first_intent.txt)

Can you provide more details if the sample app should actually work as per my understanding?

**Comment by davehorton** [comment]
can you confirm you have built the latest mod_dialogflow?  I believe I fixed this bug earlier this week

**Comment by voipterminator** [comment]
Sorry for delay, it took me some time as we had troubles to install the recent version via ansible role.
The answer is yes - we have built the latest mod_dialogflow from github.

**Comment by davehorton** [comment]
interesting, because I had the same issue, committed a fix and now I don't have the issue anymore.  Your app needs to restart a dialog after every response are you doing that?

If so, please provide a log from freeswitch showing the entire call, with loglevel at debug.  

you can email me at daveh @ drachtio.org if you want to send privately

**Comment by davehorton** [comment]
oh, sorry, I see you already provided some logs.  Let  me have a look at those and will respond

**Comment by davehorton** [comment]
yes, from the freeswitch logs this looks like exactly the same problem I had.  Let me check to make sure I've checked in the fix..

**Comment by davehorton** [comment]
Hmm, can't see the problem.  Is there any way I can point one  of my servers to execute this specific dialogflow agent?  I would need some temp credentials to be able to do that....email me offline at the email above if you want me to pursue this way of troubleshooting it

**Comment by voipterminator** [comment]
Detailed email sent. Waiting for instructions.

**Comment by davehorton** [comment]
hmm....email not yet received..

**Comment by davehorton** [comment]
oh, that is why I was asking if  you were building from the latest code (not the latest ansible script).

The latest ansible script does not pull the latest code.

Remove [this line](https://github.com/davehorton/ansible-role-fsmrf/blob/30e8ddacaaa28058f898df8d1d65b5c525f373d5/tasks/main.yml#L62), so that you are pulling the latest from the repo.  Rebuild and test.

NB: I am about to check in some major changes to that ansible role shortly to build the latest freeswitch (v1.10.1) and dialogflow v2 api.  But for now if you simply build the latest code it should work

**Comment by voipterminator** [comment]
I do confirm the issue is resolved in both cases:
- setting up specific version of custom FS modules did the trick
- up-to-date version of the Ansible role also worked fine. That includes update to FS 1.10.x

**Comment by davehorton** [comment]
Great!
